name: Update README with Repos

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update README
      run: |
        # Fetch public repositories
        repos=$(curl -s https://api.github.com/users/tbarron-xyz/repos | jq -r '.[] | select(.private == false) | "- [\(.name)](\(.html_url)): \(.description // "No description available")"')

        # Replace the repos section in README.md
        sed -i '/<!--START_SECTION:repos-->/,/<!--END_SECTION:repos-->/c\<!--START_SECTION:repos-->\n'"$repos"'\n<!--END_SECTION:repos-->' README.md

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update README with latest public repositories"
          git push
        fi
